### ISSUE TITLE
選択したソート順が、青反転してない

### ISSUE THREAD

**Issue by akagane99** [NetCommons3/Bbses#1]
細かい部分だけど、とりあえず報告。
### 画面

![bbs](https://cloud.githubusercontent.com/assets/2756509/7874944/a036e092-05f1-11e5-8160-e2a483d3623b.PNG)
### 例：表示件数のdropdownは青反転してる

![bbs2](https://cloud.githubusercontent.com/assets/2756509/7874961/c8964b22-05f1-11e5-9448-6f2618ae352f.PNG)

**Comment by s-nakajima** [comment]
青反転しない方向で、統一
